using Autodesk.AutoCAD.ApplicationServices;
using Autodesk.AutoCAD.DatabaseServices;
using Autodesk.AutoCAD.EditorInput;
using Autodesk.AutoCAD.Geometry;
using Autodesk.ProcessPower.DataLinks;
using Autodesk.ProcessPower.DataObjects;
using Autodesk.ProcessPower.PlantInstance;
using Autodesk.ProcessPower.ProjectManager;
using Autodesk.Windows;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Specialized;
using System.IO;
using System.Net.Http;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using static Stage7.InitialForm;

//LESSONS:
/*One huge important lesson: UI buttons and tools are just for human interaction. You should not put your code directly behind the button click.
Instead, you should create a separate method for the code and call that method in the button click. This is the true architectural way of coding.
Also, if you need to run the same code in different circumstances, you just call the method and not fake a button click.*/

/*If I want to point out an important thing about the whole diagram of our interaction with AI, I want you to look at the payload. You are instructing the AI to give you specific data and then you use
 that data. Reread the payload and see how after receiving the response, you use commandJson["Command"], or commandJson["RowID"] and so on. This is the point.*/

/* I wrote a code for the chatbox to freely communicate with the AI. Following is the code so you would keep it:
 * 
private async Task<string> CallGeminiAPI(string UserMessage)
        //Here we are trying to communicate with Gemini AI.
        {
            string APIkey = "AIzaSyDSMs8mFXDAtoaSNc5BqAYY3rctaw3o3ZU";
            string url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={APIkey}";
            //I suppose this is the URL for calling the Gemini API.

            var payloadData = new
            {
                systemInstruction = new
                {
                    parts = new[] { new { text = "You are a direct, highly technical engineering assistant. Answer on point and briefly. Do not use markdown formatting." } }
                    //This is the instruction part where you are prepping Gemini to answer in a specific way.
                },
                contents = new[]
                {
                new { parts = new[] { new { text = UserMessage } } }
                //Here we are using the user's actual entered text.
                }
            };
            string jsonPayload = JsonConvert.SerializeObject(payloadData);
            //This is all to create the body in which we determine the Instructions we want to give to Gemini before producing any reply and the content.

            StringContent httpContent = new StringContent(jsonPayload, Encoding.UTF8, "application/json");
            //And now this is the complete body consisting of the JSON payload, encoding, and content type.

            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

            try
            {
                HttpResponseMessage response = await _httpClient.PostAsync(url, httpContent);
                //The whole reason we studied Async/Await. Now without freezing the UI, autoCAD will keep running while this method is stopped here till the results came.
                //BTW, this is where you are sending (POSTing) your request to Gemini. You can also use GetAsync if you want to send a GET request.

response.EnsureSuccessStatusCode();
//Do you remember the status code? If the server send a code saying that something went wrong, this line will throw an exception and we will catch it in the catch block.

string rawJsonResponse = await response.Content.ReadAsStringAsync();
//This is what we call Unpacking. We received the response from the server, but it is in a format that we cannot use.
//So we need to unpack it to get the actual data we want which is the text generated by Gemini.

JObject jsonDoc = JObject.Parse(rawJsonResponse);
string aiAnswer = jsonDoc["candidates"][0]["content"]["parts"][0]["text"].ToString();
return aiAnswer;
            }

            catch (System.Exception ex)
            {
                return $"NETWORK ERROR: {ex.Message}";
            }
        }

        private async void btnExecute_Click(object sender, RoutedEventArgs e)
        {
            Autodesk.AutoCAD.Internal.Utils.SetFocusToDwgView();

            string userMessage = txtCommandInput.Text.Trim();

            if (string.IsNullOrEmpty(userMessage)) return;

            txtChatHistory.AppendText($"\nYou: {userMessage}");
            txtCommandInput.Clear();
            txtChatHistory.AppendText($"\nWaiting for M.A AI to respond...");
            txtChatHistory.ScrollToEnd();
            //All of these are self explanatory. Just updating the UI to show the user's message and clear the input box and show a waiting message.

            try
            {
                string aiResponse = await CallGeminiAPI(userMessage);
                //Exact stage in which you are waiting for Gemini to respond (without freezing the UI).

                txtChatHistory.Text = txtChatHistory.Text.Replace("\nWaiting for M.A AI to respond...", $"\nM.A AI: {aiResponse}");
            }
            catch (System.Exception ex)
            {
                txtChatHistory.Text = txtChatHistory.Text.Replace("\nWaiting for M.A AI to respond...", $"\nM.A AI: {ex.Message}"); ;
            }
        }*/

/* I also wrote a code in which I (the coder) will perform the text splitting and then connecting it to the switch command. It is not very usefull, but I want to keep it here:
        private async void btnExecute_Click(object sender, RoutedEventArgs e)
        {
            Autodesk.AutoCAD.Internal.Utils.SetFocusToDwgView();
            //You can ignore the code above, but we both know that it is for setting the focus to the drawing view so the user can interact with the drawing.

            string RawInput = txtCommandInput.Text.ToLower().Trim();

            if (string.IsNullOrEmpty(RawInput)) return;

            string[] Tokens = RawInput.Split(new char[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);
            //You know the intent behind this, but why this specific syntax? Why not just Split(' ')? The reason is that if the user types multiple spaces between
            //the command and the argument, you would get empty tokens in your array which might cause errors later on. By using StringSplitOptions.RemoveEmptyEntries,
            //you are telling the Split method to ignore any empty tokens and only return the valid ones. And the reason that we created new char[] is that the
            //Split method requires an array of characters as the separator, even if you only have one separator character.

if (Tokens.Length == 0) return;

if (Enum.TryParse(Tokens[0], true, out CommandType MyCommand))
//This is where you check either the entered command is in your target predefined list or not.
{
    switch (MyCommand)
    {
        case CommandType.Zoom:
            if (Tokens.Length < 2)
            {
                Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
                ed.WriteMessage($"\nPlease provide a Row ID for the Zoom command.\n");
                return;
            }
            else
            {
                if (int.TryParse(Tokens[1], out int TargetRowID))
                {
                    ZoomtoRowID(TargetRowID);
                }
                else
                {
                    Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
                    ed.WriteMessage($"\nEntered Row ID cannot be found.\n");
                    return;
                }
            }
            break;

        case CommandType.Move:
            if (Tokens.Length < 3)
            {
                Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
                ed.WriteMessage($"\nPlease provide RowID, Movement direction and distance.\n");
                return;
            }
            else
            {
                if (double.TryParse(Tokens[1], out double dist))
                {
                    if (Enum.TryParse(Tokens[2], true, out MoveDirection TargetDirection))
                    {
                        switch (TargetDirection)
                        {
                            case MoveDirection.X:
                                MoveRowID(dist, 0, 0);
                                break;

                            case MoveDirection.Y:
                                MoveRowID(0, dist, 0);
                                break;

                            case MoveDirection.Z:
                                MoveRowID(0, 0, dist);
                                break;
                        }
                    }
                    else
                    {
                        Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
                        ed.WriteMessage($"\nEnter a valid move direction.\n");
                        return;
                    }
                }
                else
                {
                    Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
                    ed.WriteMessage($"\nEnter a correct distance number.\n");
                    return;
                }
            }
            break;

        case CommandType.Unknown:
            break;
    }
}
else
{
    Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
    ed.WriteMessage($"\nUnknown command.\n");
}


        }*/

namespace Stage7
{
    /// <summary>
    /// Interaction logic for InitialForm.xaml
    /// </summary>
    public partial class InitialForm : System.Windows.Controls.UserControl
    {
        public InitialForm()
        {
            InitializeComponent();

            //List of properties for the property editor combo box.
            cmbPropNames.Items.Add("Size");
            cmbPropNames.Items.Add("Spec");
            cmbPropNames.Items.Add("LineNumberTag");
            cmbPropNames.Items.Add("InsulationThickness");
            cmbPropNames.Items.Add("InsulationType");
            cmbPropNames.Items.Add("Status");
            cmbPropNames.Items.Add("Material");

            cmbPropNames.SelectedItem = cmbPropNames.Items[0];
        }

        private static readonly HttpClient _httpClient = new HttpClient();
        /* The sweet subject of HTTP: HTTP is the language of the internet. You want to move data through net, you gotta speak the language. This language consists of two phases: the request and
        the response which are self explanatory. The request has also 3 parts: 1- The verb-What you want? GET or POST (so far these two suffice) which again are self explanatory.
        2- The header-In which you enter metadata about your request like API key, or the content type. 3- The Body-The actual data you are sending.
        HttpClient is C# object that creates this Http request, sends it to your network adaptor and waits for the result. Thats it!
        Now the response: The party on your URL (receiver) will get the request, evaluate it and send back a response consisting of a status code (a code telling what actually happened. Was it 
        successfull? The server crashed or ...?*/

        private async Task<string> CallGeminiAPI(string UserMessage)
        //Here we are trying to communicate with Gemini AI.
        {
            string APIkey = "AIzaSyDYPEQvg8tw87B4TaKuFm0Bl_zzK4Dsqd4";
            string url = $"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={APIkey}";
            //I suppose this is the URL for calling the Gemini API.

            List<CompData> TargetItems = SelectedItems();
            //No biggy here. You just called your method, which takes the properties of selected items in the model.

            string contextualJson = JsonConvert.SerializeObject(TargetItems, Formatting.Indented);
            /*This will convert your List to a JSON string. The formatting part is just to make the JSON string more readable for you when you see it in the logs.
             * It does not affect the way Gemini read it.*/

            var payloadData = new
            {
                systemInstruction = new
                {
                    parts = new[] { new { text = "You are an AutoCAD command translator (if asked, introduce yourself as Mehdi's AI assistant). The user will type natural language. Translate their intent into a strict JSON object. " +
                                                 "If the user asks a general question, gives an invalid command, or just wants to chat, set Command to 'Chat' and put your response" +
                                                 "entirely inside the 'Description' field and help him with brief responses." +
                                                 "Allowed Commands: 'Zoom', 'Chat', 'Move'. " +
                                                 "Allowed Axes for Move: 'X', 'Y', 'Z'. " +
                                                 "Format for Move: {\"Command\": \"Move\", \"Distance\": 2000, \"Axis\": \"Z\", \"Description\": \"Briefly state why you moved this based on the context.\"} " +
                                                 "Format for Zoom: {\"Command\": \"Zoom\", \"RowID\": 12345, \"Description\": \"Briefly state what component you zoomed to.\"} " +
                                                 "CRITICAL RULE: Return ONLY valid, raw JSON. Do not use markdown formatting (like ```json). Do not add any conversational text." +
                                                 $"\nCURRENT MODEL SELECTION CONTEXT:\n{contextualJson}"
                                        }
                                    }
                },
                /*The most important part of the whole communication with AI agent is this instructions. Because if it does not response in the format that we set the C# code to work with,
                everything will fall apart. We need the EXACT format for C# input to work and it is imperative that AI follows that without exception!*/

                contents = new[]
                {
                new { parts = new[] { new { text = UserMessage } } }
                //Here we are using the user's actual entered text.
                }
            };
            string jsonPayload = JsonConvert.SerializeObject(payloadData);
            /*Now we convert the custom object that we created to a JSON string because the HttpClient only speak in strings.
            So you create your custom object in C# with the properties and format you want, then you convert it to JSON string and send it to the AI.*/

            StringContent httpContent = new StringContent(jsonPayload, Encoding.UTF8, "application/json");
            //And now this is the complete body consisting of the JSON payload, encoding, and content type.

            System.Net.ServicePointManager.SecurityProtocol = System.Net.SecurityProtocolType.Tls12;

            try
            {
                HttpResponseMessage response = await _httpClient.PostAsync(url, httpContent);
                /*The whole reason we studied Async/Await. Now without freezing the UI, autoCAD will keep running while this method is stopped here till the results came.
                BTW, this is where you are sending (POSTing) your request to Gemini. You can also use GetAsync if you want to send a GET request.*/

                response.EnsureSuccessStatusCode();
                //Do you remember the status code? If the server send a code saying that something went wrong, this line will throw an exception and we will catch it in the catch block.

                string rawJsonResponse = await response.Content.ReadAsStringAsync();
                /*This and what comes after, is what we call Unpacking. We received the response from the server, but it is in a format that we cannot use.
                So we need to unpack it to get the actual data we want which is the text generated by Gemini.*/

                JObject jsonDoc = JObject.Parse(rawJsonResponse);
                string aiAnswer = jsonDoc["candidates"][0]["content"]["parts"][0]["text"].ToString();
                /*Note that this is the first level of unpacking. Remember the FEDEX box analogy? First you are getting the paper outside of the box and throwing away the box
                , Bubble wraps, Manifest and all the shit your do not need. But the pieace of paper also is not what you want, thats why tou unpack that again in the dedicated btnExecute.*/

                return aiAnswer;
            }

            catch (System.Exception ex)
            {
                return $"NETWORK ERROR: {ex.Message}";
            }
        }

        private async void btnExecute_Click(object sender, RoutedEventArgs e)
        {
            Autodesk.AutoCAD.Internal.Utils.SetFocusToDwgView();
            //You can ignore the code above, but we both know that it is for setting the focus to the drawing view so the user can interact with the drawing.
            
            Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;

            string userMessage = txtCommandInput.Text.ToLower().Trim();

            if (string.IsNullOrEmpty(userMessage)) return;

            txtChatHistory.AppendText($"\nYou: {userMessage}");
            txtChatHistory.AppendText($"\nWaiting for M.A AI to respond...");
            txtChatHistory.ScrollToEnd();
            txtCommandInput.Clear();

            string aiResponse = "";
            //It is defined outside the TRY for a reason! (so if the TRY crashed, we can still use it for printing the error message)

            try
            {
                aiResponse = await CallGeminiAPI(userMessage);
                //The part that we are waiting for Gemini to respond (without freezing the UI).

                JObject commandJson = JObject.Parse(aiResponse);
                //2nd unpacking. Here we are going to get what we want for the switch command. We are getting the just of the response so we can direct it to the proper command.

                string AIdescription = commandJson["Description"]?.ToString();
                //This block above would give an extra discreption from the AI to the user about what the user asked.

                /*One other important lesson in the above syntaxt is the Null-Conditional Operator "?".
                You know that if the Description was to be empty, you will receive an exception for trying to .ToString a null.
                "?" character acts as a IF. If it was null, it will not try to do the .ToString and it will just return null,
                but if it was not null, it will do the .ToString and return the value.*/

                txtChatHistory.Text = txtChatHistory.Text.Replace("\nWaiting for M.A AI to respond...", $"\nM.A AI: {AIdescription}");

                string commandString = commandJson["Command"]?.ToString();
                //Extract the COMMAND variable from the JSON. I really want to explain more, but at the time that I wrote this, I was decided that I do not need to go deeper than this!

                if (Enum.TryParse(commandString, true, out CommandType MyCommand))
                //This is where you check either the entered command is in your target predefined list or not.
                {
                    switch (MyCommand)
                    {
                        case CommandType.Zoom:
                            int ZoomID= commandJson["RowID"].Value<int>();
                            ZoomtoRowID(ZoomID);
                            break;

                        case CommandType.Move:
                            double dist = commandJson["Distance"].Value<double>();
                            string axisStr = commandJson["Axis"]?.ToString();

                            if (Enum.TryParse(axisStr, true, out MoveDirection TargetDirection))
                            {
                                switch (TargetDirection)
                                {
                                    case MoveDirection.X: MoveRowID(dist, 0, 0); break;
                                    case MoveDirection.Y: MoveRowID(0, dist, 0); break;
                                    case MoveDirection.Z: MoveRowID(0, 0, dist); break;
                                }
                            }
                            else
                            {
                                ed.WriteMessage($"\nAI provided an unknown axis: {axisStr}\n");
                                //And here is why you NEVER EVER trust the AI output. It may hallucinate!
                            }
                            break;

                        case CommandType.Unknown:
                            ed.WriteMessage("\nAI returned 'Unknown' command type.\n");
                            break;

                        case CommandType.Chat:
                            break;
                    }
                    ed.WriteMessage("\nAI Execution Complete.\n");
                }
                else
                {
                    ed.WriteMessage($"\nFailed to map AI output to CommandType Enum. Output was: {commandString}\n");
                }
            }

            catch (System.Exception ex)
            {
                txtChatHistory.Text = txtChatHistory.Text.Replace("\nWaiting for M.A AI to respond...", $"\nM.A AI: {ex.Message}\n");
            }
        }

        public enum CommandType
        /*So far we understood that the point of this enum is to limit the choices of the user. Yet I do not know what is all the fuss about it and why
        it is preferred over using strings and switch case. Guess we find out.*/
        {
            Zoom,
            Move,
            Chat,
            Unknown,
        }

        public enum MoveDirection
        {
            X,
            Y,
            Z,
        }

        private void RunInTransaction(Action toolTask)
        /*With this method (toolTask), we are going to create the initial fancy steps of interacting with AutoCAD once,
        and then use it everywhere we want to change the DWG. For example, in here, you have 4 buttons to do 4 different
        things. Instead of repeating the same code for each button, you can just call this method. Action here is a delegate,
        which means it purpose is to be used for a method (unlike other methods which will receive variables).*/
        {
            Document doc = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument;
            /*The reason for the long Autodesk.AutoCAD line is that otherwise, there would be a conflict between the Document class in AutoCAD
            and the Document class in WPF, since we are using both of them in this code, we need to specify
            which one we are using by using the full namespace.*/

            if (doc == null) return;
            //Just a safety check for the user not to click without opening a drawing.

            Database db = doc.Database;
            Editor ed = doc.Editor;
            using (DocumentLock docLock = doc.LockDocument())
            /*When you type a command in AutoCAD, it locks the document to prevent other commands from interfering with it.
            If you want to run a command in your palette which is floating freely without locking the document first,
            you would get an error saying that the document is locked by another command which is your palette command.
            so you need to lock the document first before running any command in your palette.
            as for the "using", we did that so the code would automatically dispose the lock after it is done executing.
            since if we do not dispose the lock, it would stay locked and you would not be able to run any other command
            in AutoCAD until you close the drawing.*/
            {
                using (Transaction tr = db.TransactionManager.StartTransaction())
                {
                    try
                    //From now on you gotta use try and cath more often. You know what they are for, so stop being lazy and use them.
                    {
                        toolTask();
                        tr.Commit();
                    }
                    catch (System.Exception ex)
                    {
                        ed.WriteMessage($"Error: {ex.Message}");
                    }
                }
            }
        }

        private void btnTagCleaner_Click(object sender, RoutedEventArgs e)
        {
            RunInTransaction(() =>
            /*By doing this, you are actually saying that I want all the code that I wrote in the RunInTransaction method to be executed
            and the following code block should replace the "toolTask" in the RunInTransaction method.*/
            {
                PlantProject currentProject = PlantApplication.CurrentProject;
                Project pipingProj = currentProject.ProjectParts["Piping"];
                DataLinksManager dlm = pipingProj.DataLinksManager;
                Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;

                PnPDatabase pnpDb = dlm.GetPnPDatabase();
                /*Now why we didnt use the dlm to get the database directly?
                It seems we could (like the method you used for SpecChanger), but it never hurts to have another way of communicating with the database.
                Using PnPDatabase is more direct and it is easier to understand the structure of the database.*/
                
                //foreach (PnPTable table in pnpDb.Tables)
                //{
                //    ed.WriteMessage($"\nTable found: {table.Name}");
                //}
                /*Just a temp loop for you to find every table in the database and see what they are called. It is like you are exploring the database for the first time.*/

                PnPTable valveTable = pnpDb.Tables["Valve"];
                /*Now that you have PnPDatabase, you can directly access the tables in the database.
                It is like having a direct line to the database without going through the DataLinksManager. You get to know what tables are there
                and what properties they save in each table so it seems in the the future, it can make you more efficient in accessing the data.*/

                PnPRow[] allValves = valveTable.Select();
                /*Now you have the table, you can select all the rows in the table. You can also select the rows with specific criteria such as
                size, spec, etc. the syntaxt for this example is: PnPRow[] allValves = valveTable.Select("Size = '6\"'");*/

                foreach (PnPRow valveRow in allValves)
                {
                    int rowId = valveRow.RowId;
                    Object CurTagRaw = valveRow["Tag"];
                    string CurTag = CurTagRaw != null ? CurTagRaw.ToString() : "";
                    //Again another null check. Null check is very important for us!

                    if (string.IsNullOrWhiteSpace(CurTag) || !CurTag.StartsWith("V-"))
                    /*There is a point here. the null does not have StartsWith method. So if you put the StartsWith first, you might get an error.
                    So we move the null check first, and if it is not null, then we check for the StartsWith. This is a common practice to avoid null reference exceptions.*/
                    {
                        ed.WriteMessage($"\nInvalid tag found: {CurTag} - Current row ID: {rowId}\n");
                    }
                }
                ed.WriteMessage($"\nCheck completed.\n");
            });

        }

        private void btnPropEditor_Click(object sender, RoutedEventArgs e)
        {
            string TargetProp = cmbPropNames.SelectedItem.ToString();
            string TargetVal = txtPropValue.Text;
            if (string.IsNullOrEmpty(TargetProp)) return;

            Autodesk.AutoCAD.Internal.Utils.SetFocusToDwgView();
            /*There is a huge concept here. Although your WPF is docked inside the ACP3D, but it is a windows app. When you click on it, the focus will be
            on the WPF and not on the ACP. In you code, you are trying to prompt the user to select an entity in the drawing while your focus is on the WPF.
            two things might happen: either the user have to cliclk twice to move the focus or the ACP freezes.
            This SetFocusToDwgView is the brute force to move the focus to the DWG.*/

                Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
            ed.WriteMessage("Property Editor button clicked!");

            PromptEntityOptions SelectedEntity = new PromptEntityOptions("\nSelect an object to change the property: ");
            SelectedEntity.SetRejectMessage("\nOnly selected objects are allowed.");
            SelectedEntity.AddAllowedClass(typeof(Entity), false);
            PromptEntityResult ResultedEntity = ed.GetEntity(SelectedEntity);
            if (ResultedEntity.Status != PromptStatus.OK) return;
            //The whole process of prompting the user to select an entity.
            /*One other important rule here: If the code is waiting for a human, it goes outside. If the code is actively altering data, it goes inside.*/

            RunInTransaction(() =>
            {
                PlantProject currentProject = PlantApplication.CurrentProject;
                Project pipingProj = currentProject.ProjectParts["Piping"];
                DataLinksManager dlm = pipingProj.DataLinksManager;

                int rowID = dlm.FindAcPpRowId(ResultedEntity.ObjectId);

                if (rowID > 0)
                {
                    StringCollection UpdateLabels = new StringCollection();
                    UpdateLabels.Add(TargetProp);
                    StringCollection UpdateValues = new StringCollection();
                    UpdateValues.Add(TargetVal);

                    dlm.SetProperties(rowID, UpdateLabels, UpdateValues);
                }
            });
        }

        private void btnValidate_Click(object sender, RoutedEventArgs e)
        {
            RunInTransaction(() =>
            {
                PlantProject currentProject = PlantApplication.CurrentProject;
                Project pipingProj = currentProject.ProjectParts["Piping"];
                DataLinksManager dlm = pipingProj.DataLinksManager;
                Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;

                PnPDatabase pnpDb = dlm.GetPnPDatabase();
                PnPTable AllCompTable = pnpDb.Tables["PipeRunComponent"];
                /*There is a huge concept here. You learnt about the structure of AutoCAD Plant 3D database tables. You know now that what are the major tables
                and what kind of data they save. What tables are grandparents and what tables are the children. In the above line, we are accessing one of the
                tables for our specific purpose which are piping components.*/

                PnPRow[] allComp = AllCompTable.Select();

                foreach (PnPRow comp in allComp)
                {
                    string CompLineNum = comp["LineNumberTag"] != null ? comp["LineNumberTag"].ToString() : "";
                    string CompType = comp["PartCategory"] != null ? comp["PartCategory"].ToString() : "";
                    string CompLoc = comp["Position X"] + "," + comp["Position Y"] + "," + comp["Position Z"];
                    string CompID = comp.RowId.ToString();
                    //We are just gerring some data to show the user what components are we tracking.
                    
                    var part1Connections = dlm.GetRelatedRowIds("P3dPartConnection", "Part1", comp.RowId, "Part2");
                    var part2Connections = dlm.GetRelatedRowIds("P3dPartConnection", "Part2", comp.RowId, "Part1");
                    /*The core lesson of this practice is here. Accessing data via GetRelatedRowIds. It is the exact same function of VLOOKUP in excel.
                    At first you need to know what table are you getting the data from, what are the column lables and what each column store.
                    When you mastered that, you just querry the data you wanted from it and check the data: here we are seeking components which none of its ports
                    is connected to any other component. When we find these (Floating Components), we report them to the user with their line number, type and location.*/

                    int totalConnections = part1Connections.Count + part2Connections.Count;

                    if (totalConnections == 0)
                    {
                        ed.WriteMessage($"\nComponent with ID {CompID} and Line Number {CompLineNum} of type {CompType} at location {CompLoc} has no connections.\n");
                    }
                }


            });
        }

        private void btnReport_Click(object sender, RoutedEventArgs e)
        {
            using var ReportSaver = new SaveFileDialog();
            ReportSaver.Title = "Export the report";
            ReportSaver.Filter = "Text Files|*.txt|CSV Files|*.csv";
            ReportSaver.InitialDirectory = "D:\\";

            if (ReportSaver.ShowDialog() == DialogResult.OK)
            {
                RunInTransaction(() =>
                {
                    PlantProject currentProject = PlantApplication.CurrentProject;
                    Project pipingProj = currentProject.ProjectParts["Piping"];
                    DataLinksManager dlm = pipingProj.DataLinksManager;
                    Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;

                    PnPDatabase pnpDb = dlm.GetPnPDatabase();
                    PnPTable valveTable = pnpDb.Tables["Valve"];
                    PnPRow[] allValves = valveTable.Select();

                    List<string> UserReport = new List<string>();

                    UserReport.Add("Tag,Size,Spec");

                    foreach (var valve in allValves)
                    {
                        string CompData = $"{valve["Tag"]},{valve["Size"]},{valve["Spec"]}";
                        UserReport.Add(CompData);
                    }

                    ed.WriteMessage("Report button clicked!");

                   File.WriteAllLines(ReportSaver.FileName, UserReport);

                });
            }
        }

        private void btnZoom_Click(object sender, RoutedEventArgs e)
        {
            if (int.TryParse(txtZoomID.Text, out int TargetRowID))
            {
                ZoomtoRowID(TargetRowID);
            }
            else
            {
                RunInTransaction(() =>
                {
                    Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
                    ed.WriteMessage("\nInvalid ID input. Please enter a valid integer.");
                });
            }
        }
        private void ZoomtoRowID(int rowID)
        {
                RunInTransaction(() =>
                {
                    PlantProject currentProject = PlantApplication.CurrentProject;
                    Project pipingProj = currentProject.ProjectParts["Piping"];
                    DataLinksManager dlm = pipingProj.DataLinksManager;
                    Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;

                    var TargetObjectIDRaw = dlm.FindAcPpObjectIds(rowID);
                    /*Before understanding What we've done here, you should know the difference between RowID and ObjectID.
                    RowID is the ID of the row in the database, while ObjectID is the ID of the object in the AutoCAD drawing. Several points:
                    1- ObjectID changes everytime you open and close ACP3D.
                    2- Each RowID MAY point to several ObjectIDs. Thats why the output of this method would be an ACP3D special object type for ARRAYS*/

                    ObjectId TargetObjectID = ObjectId.Null;

                    foreach (var objId in TargetObjectIDRaw)
                    /*The reason we are doing it is that we do not have access to any specific member of this ACP3D custom array.
                    So we loop through it and choose the first one and then break out of the loop.*/
                    {
                        TargetObjectID = dlm.MakeAcDbObjectId(objId);
                        //This is obvious. We turn the custom object ID to the AutoCAD ObjectID so we can use it to querry the drawing.

                        if (TargetObjectID != ObjectId.Null)
                        {
                            break;
                        }
                    }

                    if (TargetObjectID != ObjectId.Null)
                    {
                        Transaction tr = HostApplicationServices.WorkingDatabase.TransactionManager.TopTransaction;
                        /*You know that you cannot access the tr inside your RunInTransaction method, but ACP3D has a special method to access the current open transaction.
                        Line of code above is how to use this*/

                        Entity TargetEntity = tr.GetObject(TargetObjectID, OpenMode.ForRead) as Entity;
                        if (TargetEntity == null) return;

                        Extents3d TargetExtents = TargetEntity.GeometricExtents;
                        //This is interesting. You have an ObjectID and by only that, you can have the cooridnates of a box which contains your 3d model completly.

                        ViewTableRecord CurrView = ed.GetCurrentView();
                        double centerX = (TargetExtents.MinPoint.X + TargetExtents.MaxPoint.X) / 2;
                        double centerY = (TargetExtents.MinPoint.Y + TargetExtents.MaxPoint.Y) / 2;
                        double centerZ = (TargetExtents.MinPoint.Z + TargetExtents.MaxPoint.Z) / 2;
                        //these two are obvious. We are pointing to the center of the box X and Y.

                        double width = TargetExtents.MaxPoint.X - TargetExtents.MinPoint.X;
                        double height = TargetExtents.MaxPoint.Y - TargetExtents.MinPoint.Y;
                        /*About these two: the width and height of the box is not the width and height of the object.
                        It is the width and height of the box that contains the object. Therefore, you calculate this based on your target volume*/

                        CurrView.Target = new Point3d(centerX, centerY, centerZ);
                        CurrView.CenterPoint = Point2d.Origin;
                        CurrView.Width = width * 1.5;
                        CurrView.Height = height * 1.5;
                        /*Several points here: 1-There is a difference between Target and CenterPoint. Target is rotating reference point, while the CenterPoint
                        is the distance you panned from that reference point. 2- We multiply 1.5 for width and height to prevent the object touching the edges of
                        screen.*/

                        ed.SetCurrentView(CurrView);
                        ed.UpdateScreen();
                        ed.SetImpliedSelection(new ObjectId[] { TargetObjectID });
                        //The syntax for changing the view and updating the screen to show the new view and actually selecting the element.

                    }
                    else
                    {
                        ed.WriteMessage($"\nNo AutoCAD object found for Row ID {rowID}.");
                    }

                });
        }

        private void MoveRowID(double Xdist, double Ydist, double Zdist)
        {
            Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;

            RunInTransaction(() =>
            {
                Vector3d MoveVector = new Vector3d(Xdist, Ydist, Zdist);

                PromptSelectionResult SelRes = ed.SelectImplied();

                if (SelRes.Status != PromptStatus.OK)
                {
                    ed.WriteMessage("\nNo object selected to move.");
                    return;
                }

                SelectionSet selSet = SelRes.Value;

                Transaction tr = HostApplicationServices.WorkingDatabase.TransactionManager.TopTransaction;
                /* I am gonna tell this again. When you create a Trasaction at the top of this code, you already opened a transaction. Meaning that you cannot open another one inside it
                whenever you want. You are gonna use that opened transaction and do what you want.*/

                foreach (SelectedObject selObj in selSet)
                {
                    Entity ent = tr.GetObject(selObj.ObjectId, OpenMode.ForWrite) as Entity;

                    ent.TransformBy(Matrix3d.Displacement(MoveVector));
                }
            });
        }

        public List<CompData> SelectedItems()
        {
            Editor ed = Autodesk.AutoCAD.ApplicationServices.Application.DocumentManager.MdiActiveDocument.Editor;
            PlantProject currentProject = PlantApplication.CurrentProject;
            Project pipingProj = currentProject.ProjectParts["Piping"];
            DataLinksManager dlm = pipingProj.DataLinksManager;

            PromptSelectionResult SelRes = ed.SelectImplied();
            //This is how we get the selected elements.

            SelectionSet selSet ;
            List<CompData> SelItems = new List<CompData>();

            if (SelRes.Status != PromptStatus.OK)
            {
                //txtChatHistory.AppendText("\nNo object selected.\n");
                return SelItems;
            }

            else
            {
                selSet = SelRes.Value;
                foreach (SelectedObject selObj in selSet)
                {
                    CompData RawData = new CompData();
                    //Your customized class to store the selected components data.

                    int rowID = -1;

                    try
                    {
                        rowID = dlm.FindAcPpRowId(selObj.ObjectId);
                    }

                    catch { continue; } 
                    //A very simple use of try and catch. If you know you may get exceptions that you dont care about and just want your code to run, this is what you do.
                    
                    if (rowID <= 0)
                    {
                        continue;
                    }

                    else
                    {
                        StringCollection labels = new StringCollection();
                        labels.Add("LineNumberTag");
                        labels.Add("Spec");
                        labels.Add("Size");
                        labels.Add("Tag");
                        labels.Add("Position X");
                        labels.Add("Position Y");
                        labels.Add("Position Z");

                        var results = dlm.GetProperties(rowID, labels, true);

                        RawData.ObjID = selObj.ObjectId.ToString();
                        RawData.LineNo = results[0];
                        RawData.Spec = results[1];
                        RawData.Size = results[2];
                        RawData.Tag = results[3];
                        double.TryParse(results[4], out double coordX);
                        double.TryParse(results[5], out double coordY);
                        double.TryParse(results[6], out double coordZ);
                        RawData.CoordX = coordX;
                        RawData.CoordY = coordY;
                        RawData.CoordZ = coordZ;

                        SelItems.Add(RawData);
                    }
                }
                return SelItems;
            }
        }
    }
}
